services:
  # 1. Хранилище графов (Persistent State)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: gatekeeper
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 15

  # 2.1 Эфемерный мигратор графа (Init Container)
  spicedb-migrate:
    image: authzed/spicedb:latest
    command: datastore migrate head --datastore-engine postgres --datastore-conn-uri "postgres://postgres:supersecretpassword@postgres:5432/gatekeeper?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  # 2.2 Графовый движок (ReBAC Zanzibar)
  spicedb:
    image: authzed/spicedb:latest
    command: serve --grpc-preshared-key "devsecops-secret-key" --datastore-engine postgres --datastore-conn-uri "postgres://postgres:supersecretpassword@postgres:5432/gatekeeper?sslmode=disable"
    ports:
      - "50051:50051"
    depends_on:
      spicedb-migrate:
        condition: service_completed_successfully

  # 3. Кэш токенов IAT и Rate Limits
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  # 4. Транспортный слой сканеров (Event Broker)
  nats:
    image: nats:2.9-alpine
    command: ["-js"] 
    ports:
      - "4222:4222"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - postgres
      - spicedb
    environment: # [SECURITY] Инжектируем секрет из .env хоста в изолированную память контейнера
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      # [SECURITY] Прокидываем ключ в режиме Read-Only (ro), не вшивая его в сам образ
      - ./key.pem:/app/key.pem:ro

  scanner:
    build:
      context: .
      dockerfile: Dockerfile.scanner
    depends_on:
      - nats
      - postgres
    volumes:
      - ./key.pem:/app/key.pem:ro

volumes:
  pg_data: