name: DevSecOps Gatekeeper CI

# Пайплайн запускается при каждом пуше в ветку main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # Имя образа формируется из имени владельца и репозитория (например, madi/devsecops-gatekeeper)
  IMAGE_NAME: xtrel/devsecops-gatekeeper

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub автоматически выдает токен для текущего репо, можно использовать его вместо ручного GHCR_PAT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Сборка и пуш API Gateway
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.api
          push: ${{ github.event_name != 'pull_request' }} # Пушим только при мердже в main
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Сборка и пуш Scanner Worker
      - name: Build and push Scanner image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.scanner
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-scanner:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-scanner:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max